# Generated by Django 5.1.1 on 2024-10-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Udata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('sub', models.CharField(max_length=90)),
            ],
        ),
    ]
